Purchase Orders
ios-cv/carshare pull request #90
Opened 2024-12-20 18:26 UTC by Scilly-guy

Fixes #63
Adds a Purchase Order (PO) field to billing accounts.
If the PO is set then it will be added to stripes custom fields on the invoice.
Users can set the PO themselves via the billing page of their profile.

2024-12-20 18:27 UTC, Scilly-guy commented
Could do with feedback after the PO is updated.

2024-12-21 12:00 UTC, grundleborg requested changes
Looks generally good, a few comments inline.

2024-12-21 12:01 UTC, grundleborg commented
Another thought: we probably need to include the PO number input as optional in the form for creating a business billing account.

2024-12-21 22:42 UTC, Scilly-guy commented on billing/views.py
> +def update_purchse_order(request, billing_account, new_purchase_order):
Ah yeah, this makes sense, should be straight forward to add that.

2024-12-21 22:47 UTC, Scilly-guy commented on billing/urls.py
> +        name="billing_update_purchase_order_prep",
yeah, this needs a more clever work around/alternative way of working, basically this is a hack to allow the template to request the first half of the url which gets the second bit (the new PO) appended via alpine. Now that I see it I feel bad for submitting it like this, might be easiest to explain in person.

2024-12-21 22:48 UTC, Scilly-guy commented on billing/tasks.py
> +        if account.business_purchase_order:
NP

2024-12-22 13:24 UTC, grundleborg submitted a review, later dismissed

2024-12-22 13:24 UTC, grundleborg commented on billing/urls.py
> +        "billing/<str:billing_account>/<str:new_purchase_order>/",
```suggestion
        "billing/<str:billing_account>/update_purchase_order/",
```

2024-12-22 13:25 UTC, grundleborg requested changes
Got in a mess and accidentally set "Approve" rather than "Request Changes" so resubmitting my review.

2025-01-02 12:30 UTC, Scilly-guy commented
I didn't go down the Alpine route and instead opted for following advice found online. Happy to rework it in the future to use Alpine but thought getting something functional sooner would be beneficial. Still need to add PO to credit card invoices.

2025-01-04 12:05 UTC, Scilly-guy reviewed
This uses code from [this codepen](https://codepen.io/ottodevs/pen/BMmdMM) which is MIT licensed, I have lightly edited it to work in this situation and changed the colour to fit the sites colour scheme.

2025-01-12 16:16 UTC, grundleborg commented on billing/forms.py
> +            "business_purchase_order": "If you have a purchase order it will be displayed on your invoices, you may change this at any time.",
```suggestion
            "business_purchase_order": "If you enter a purchase order number here it will be displayed on your invoices. You can change this at any time.",
```

2025-01-12 16:17 UTC, grundleborg commented on billing/forms.py
> +            "business_purchase_order": "If you have a purchase order it will be displayed on your invoices, you may change this at any time."
```suggestion
            "business_purchase_order": "If you enter a purchase order number here it will be displayed on your invoices. You can change this at any time."
```

2025-01-12 16:18 UTC, grundleborg commented on billing/views.py
> +    form = UpdatePurchaseOrderForm()
This doesn't appear to be used anywhere.

2025-01-12 16:23 UTC, grundleborg commented on billing/views.py
> +            if updated_billing_account in billing_accounts:
Can you add a comment here to say that this check is to make sure the user has permission to change the billing account? It wasn't immediately obvious to me, and so someone looking at it in future might not realise that this line is what protects this form against an authorization bypass.

2025-01-26 10:21 UTC, grundleborg approved these changes
LGTM. I collapsed the migrations into one before merging, and tweaked the form field label, but otherwise all good :)

2025-01-26 10:23 UTC, merged